[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
  "forge-std=lib/forge-std/src"
]
ffi = true #allows foundry to run commands directy on my machine. Try to keep off as long as possible.

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
